import Head from 'next/head';
import ThemeProvider from '@/shared/theme';

import { ToastProvider } from '@/shared/contexts/ToastContext';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <ThemeProvider>
        <ToastProvider>          
          <Component {...pageProps} />
        </ToastProvider>
      </ThemeProvider>
    </>
  );
}
